name       : python-traitlets
version    : 4.3.2
release    : 1
source     :
    - https://github.com/ipython/traitlets/archive/4.3.2.tar.gz : 370f938ad730d52272ef74f96f831cb21138f6168e46fe582fe256c35cc656ce
license    : BSD-3-Clause
component  : programming.python
summary    : A lightweight Traits like module.
description: |
    A lightweight Traits like module.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-decorator
    - python3-decorator
    - python-enum34
    - python-ipython_genutils
    - python-six
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
