name       : python-traitlets
version    : 5.1.0
release    : 8
source     :
    - https://github.com/ipython/traitlets/archive/refs/tags/5.1.0.tar.gz : ea523391b908c1ec5f2c80bb70398e7b5112d0ff825bba01a488d2106e77334d
homepage   : https://github.com/ipython/traitlets
license    : BSD-3-Clause
component  : programming.python
summary    : A lightweight Traits like module
description: |
    Traitlets is a framework that lets Python classes have attributes with type checking, dynamically calculated default values, and ‘on change’ callbacks. The package also includes a mechanism to use traitlets for configuration, loading values from files or from command line arguments. This is a distinct layer on top of traitlets, so you can use traitlets in your code without using the configuration machinery.
builddeps  :
    - python-decorator
    - python-mock
    - python-pytest
rundeps    :
    - python-decorator
    - python-six
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
