name       : python-traitlets
version    : 4.3.3
release    : 5
source     :
    - https://github.com/ipython/traitlets/archive/4.3.3.tar.gz : b686c1aadf6ee5a9ee4c22df23bc5cd5bb7b5cfa18afe092e0a139cc2f05fe2e
homepage   : https://github.com/ipython/traitlets
license    : BSD-3-Clause
component  : programming.python
summary    : A lightweight Traits like module
description: |
    Traitlets is a framework that lets Python classes have attributes with type checking, dynamically calculated default values, and ‘on change’ callbacks. The package also includes a mechanism to use traitlets for configuration, loading values from files or from command line arguments. This is a distinct layer on top of traitlets, so you can use traitlets in your code without using the configuration machinery.
builddeps  :
    - python-decorator
    - python-ipython_genutils
    - python-mock
    - python-pytest
rundeps    :
    - python-decorator
    - python-ipython_genutils
    - python-six
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
